Update remover

diff --git a/Modulos/remover b/Modulos/remover
--- a/Modulos/remover
+++ b/Modulos/remover
@@ -26,6 +26,7 @@ echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;33m KILL A USER"
 echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;33m KILL ALL USERS"
 echo -e "\033[1;31m[\033[1;36m4\033[1;31m]\033[1;33m LOCK USER"
 echo -e "\033[1;31m[\033[1;36m5\033[1;31m]\033[1;33m UNLOCK USER"
+echo -e "\033[1;31m[\033[1;36m6\033[1;31m]\033[1;33m LOG USER"
 echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m REMOVE ALL USERS"
 echo -e "\033[1;31m[\033[1;36m0\033[1;31m]\033[1;33m COME BACK "
 echo ""
@@ -211,6 +212,46 @@ else
 		usermod -U "$user" > /dev/null 2>&1
 	    echo -e "\033[1;33m USERS $user UNLOCKED \033[0m"S
 		exit 1
+	else
+		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "User $user does not exist!" ; echo "" ; tput sgr0
+	fi
+fi
+
+elif [[ "$resp" = "6" ]]; then
+clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "LOG User" ; tput sgr0
+echo ""
+echo -e "\033[1;33mLIST OF USERS: \033[0m"
+echo""
+_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
+i=0
+unset _userPass
+while read _user; do
+	i=$(expr $i + 1)
+	_oP=$i
+	[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
+	echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m"
+	_userPass+="\n${_oP}:${_user}"
+done <<< "${_userT}"
+echo ""
+num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
+echo -ne "\033[1;32mType or select a user \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
+user=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
+if [[ -z $option ]]; then
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "  Empty or invalid user!   " ; echo "" ; tput sgr0
+	exit 1
+elif [[ -z $user ]]; then
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo " Empty or invalid user! " ; echo "" ; tput sgr0
+	exit 1
+else
+	if cat /etc/passwd |grep -w $user > /dev/null; then
+		echo ""
+		# usermod -U "$user" > /dev/null 2>&1
+		# echo -e $(zgrep sshd /var/log/auth.log -h | grep -F $user)
+		zgrep sshd /var/log/auth.log -h | grep -E --color=always $user
+	    # echo -e "\033[1;33m USERS $user UNLOCKED \033[0m"S
+		read -n 1 -s -r -p "Press any key to continue"
+		exit
 	else
 		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "User $user does not exist!" ; echo "" ; tput sgr0
 	fi
