Add files via upload

diff --git a/Modulos/remover b/Modulos/remover
--- a/Modulos/remover
+++ b/Modulos/remover
@@ -22,8 +22,12 @@ clear
 tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Remove SSH User" ; tput sgr0
 echo ""
 echo -e "\033[1;31m[\033[1;36m1\033[1;31m]\033[1;33m REMOVE A USER"
-echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;33m REMOVE ALL USERS"
-echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;33m COME BACK "
+echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;33m KILL A USER"
+echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;33m KILL ALL USERS"
+echo -e "\033[1;31m[\033[1;36m4\033[1;31m]\033[1;33m LOCK USER"
+echo -e "\033[1;31m[\033[1;36m5\033[1;31m]\033[1;33m UNLOCK USER"
+echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m REMOVE ALL USERS"
+echo -e "\033[1;31m[\033[1;36m0\033[1;31m]\033[1;33m COME BACK "
 echo ""
 read -p "$(echo -e "\033[1;32mWHAT DO YOU WANT TO DO\033[1;31m ?\033[1;37m : ")" -e -i 1 resp
 if [[ "$resp" = "1" ]]; then
@@ -96,7 +100,143 @@ else
 		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "User $user does not exist!" ; echo "" ; tput sgr0
 	fi
 fi
+
+
+
+
 elif [[ "$resp" = "2" ]]; then
+clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "KILL SSH User" ; tput sgr0
+echo ""
+echo -e "\033[1;33mLIST OF USERS: \033[0m"
+echo""
+_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
+i=0
+unset _userPass
+while read _user; do
+	i=$(expr $i + 1)
+	_oP=$i
+	[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
+	echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m"
+	_userPass+="\n${_oP}:${_user}"
+done <<< "${_userT}"
+echo ""
+num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
+echo -ne "\033[1;32mType or select a user \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
+user=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
+if [[ -z $option ]]; then
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "  Empty or invalid user!   " ; echo "" ; tput sgr0
+	exit 1
+elif [[ -z $user ]]; then
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo " Empty or invalid user! " ; echo "" ; tput sgr0
+	exit 1
+else
+	if cat /etc/passwd |grep -w $user > /dev/null; then
+		echo ""
+		pkill -f "$user" > /dev/null 2>&1
+	    echo -e "\033[1;33m USERS $user KILLED \033[0m"
+		exit 1
+	else
+		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "User $user does not exist!" ; echo "" ; tput sgr0
+	fi
+fi
+
+elif [[ "$resp" = "4" ]]; then
+clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "LOCK SSH User" ; tput sgr0
+echo ""
+echo -e "\033[1;33mLIST OF USERS: \033[0m"
+echo""
+_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
+i=0
+unset _userPass
+while read _user; do
+	i=$(expr $i + 1)
+	_oP=$i
+	[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
+	echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m"
+	_userPass+="\n${_oP}:${_user}"
+done <<< "${_userT}"
+echo ""
+num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
+echo -ne "\033[1;32mType or select a user \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
+user=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
+if [[ -z $option ]]; then
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "  Empty or invalid user!   " ; echo "" ; tput sgr0
+	exit 1
+elif [[ -z $user ]]; then
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo " Empty or invalid user! " ; echo "" ; tput sgr0
+	exit 1
+else
+	if cat /etc/passwd |grep -w $user > /dev/null; then
+		echo ""
+		pkill -f $user > /dev/null 2>&1
+		usermod -L "$user" > /dev/null 2>&1
+	    echo -e "\033[1;33m USERS $user LOCKED \033[0m"S
+		exit 1
+	else
+		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "User $user does not exist!" ; echo "" ; tput sgr0
+	fi
+fi
+
+elif [[ "$resp" = "5" ]]; then
+clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "UNLOCK SSH User" ; tput sgr0
+echo ""
+echo -e "\033[1;33mLIST OF USERS: \033[0m"
+echo""
+_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
+i=0
+unset _userPass
+while read _user; do
+	i=$(expr $i + 1)
+	_oP=$i
+	[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
+	echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m"
+	_userPass+="\n${_oP}:${_user}"
+done <<< "${_userT}"
+echo ""
+num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
+echo -ne "\033[1;32mType or select a user \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: " ; read option
+user=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
+if [[ -z $option ]]; then
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "  Empty or invalid user!   " ; echo "" ; tput sgr0
+	exit 1
+elif [[ -z $user ]]; then
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo " Empty or invalid user! " ; echo "" ; tput sgr0
+	exit 1
+else
+	if cat /etc/passwd |grep -w $user > /dev/null; then
+		echo ""
+		usermod -U "$user" > /dev/null 2>&1
+	    echo -e "\033[1;33m USERS $user UNLOCKED \033[0m"S
+		exit 1
+	else
+		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "User $user does not exist!" ; echo "" ; tput sgr0
+	fi
+fi
+
+elif [[ "$resp" = "3" ]]; then
+	clear
+	tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "KILL SSH Users" ; tput sgr0
+	echo ""
+	echo -ne "\033[1;33mREALLY WISH TO KILL ALL USERS \033[1;37m[s/n]: "; read opc	
+	if [[ "$opc" = "s" ]]; then
+	echo -e "\n\033[1;33mAguarde\033[1;32m.\033[1;31m.\033[1;33m.\033[0m"
+		for user in $(cat /etc/passwd |awk -F : '$3 > 900 {print $1}' |grep -vi "nobody"); do
+			pkill -f $user > /dev/null 2>&1
+		done
+		echo -e "\n\033[1;32mSUCCESSFULLY KILLED USERS!\033[0m"
+		sleep 2
+		menu
+	else
+		echo -e "\n\033[1;31mReturning to the menu ...\033[0m"
+		sleep 2
+		menu
+	fi
+
+
+elif [[ "$resp" = "10" ]]; then
 	clear
 	tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "SRemove SSH User" ; tput sgr0
 	echo ""
@@ -120,7 +260,7 @@ elif [[ "$resp" = "2" ]]; then
 		sleep 2
 		menu
 	fi
-elif [[ "$resp" = "3" ]]; then
+elif [[ "$resp" = "0" ]]; then
 	menu
 else
 	echo -e "\n\033[1;31mOption invalid!\033[0m"
